### ISSUE TITLE
Blank page on localhost:3000 after installation

### ISSUE THREAD

**Issue by minimalex** [samueldobbie/markup#92]
Hi. I wanted to install the markup tool locally on my M1 Mac (MacBook Pro 14" with Brave Browser). After install through yarn is finished I always get the following error in the browser console: 

caught Error: supabaseUrl is required.
    at new SupabaseClient (SupabaseClient.ts:87:1)
    at createClient (index.ts:38:1)
    at ./src/utils/Supabase.ts (Supabase.ts:5:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/providers/AuthProvider.tsx (Support.tsx:23:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)

... and the page stays blank. I was not able to fix the issue myself. I am very thankful for advise :)

Thank you very much!

**Comment by lschmierer** [comment]
Looks like this project builds on supabase. You can follow the instructions to setup a local development instance here https://supabase.com/docs/guides/getting-started/local-development

I think you also need to set the REACT_APP_SUPABASE_URL and REACT_APP_SUPABASE_ANON_KEY environment variables as used in this file https://github.com/samueldobbie/markup/blob/main/src/utils/Supabase.ts

**Comment by samueldobbie** [comment]
Thanks for flagging. I'll update the README to list the steps required to setup your own Supabase instance and configure Markup to use that instance.

**Comment by samueldobbie** [comment]
Have updated the README with instructions + shared the Supabase migrations.
